seed_everything: 42
model:
  in_channels: 3
  out_channels: 1
  downsample_block:
    class_path: session_15.MaxPoolDownsampleBlock
  upsample_block:
    class_path: session_15.TransposeConvUpsampleBlock
  loss_fn:
    class_path: session_15.DiceLoss
  max_lr: 0.01
data:
  root_dir: ./data/dataset
  batch_size: 32
  num_workers: 6
trainer:
  max_epochs: 30
  log_every_n_steps: 5
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "unet-oxfordiiitpet-{epoch:02d}-{metric.val.loss:.4f}"
        monitor: metric.val.loss
        mode: min
        save_top_k: 3
        save_last: true
        verbose: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.TQDMProgressBar
      init_args:
        leave: true
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: data/logs
      name: unet-oxfordiiitpet
