type: continuous
env:
  map: ./city_map_2.jpeg
  car_width: 12
  car_height: 6
  car_max_speed: 2
  car_max_turn_angle: 20
  sensor_dist: 10
  centered_sensor_reward_scale: 5
  distance_reward_scale: 10
  speed_reward_scale: 2.5
  render_mode: rgb_array
  start_pos: [116, 19]
  waypoints:
    - [139, 331]
    - [378, 483]
    - [599, 566]
    - [647, 760]

agent:
  batch_size: 512
  discount: 0.99
  tau: 3.e-3
  policy_noise: 0.2
  noise_clip: 0.5
  policy_update_freq: 2

trainer:
  random_action_steps: 10000
  exploration_noise: 0.005
