map: ./city_map_2.jpeg
car_width: 12
car_height: 6
sensor_dist: 10
lr: 1.e-3
temperature: 50.0
temperature_min: 0.001
temperature_decay: 0.9995
turn_speed: 8
sharp_turn_speed: 20
car_speed: 2
max_consecutive_crashes: 2
batch_size: 512
gamma: 0.95
tau: 3.e-3
record_dir: ../data
