map: ./city_map_1.jpeg
car_width: 14
car_height: 8
sensor_dist: 15
lr: 1.e-3
epsilon: 1.0
turn_speed: 8
sharp_turn_speed: 20
car_speed: 2
max_consecutive_crashes: 2
batch_size: 512
gamma: 0.95
tau: 3.e-3
record_dir: ../data
